# Generated by Django 4.2.2 on 2023-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setores',
            name='nome_setor',
            field=models.CharField(max_length=50),
        ),
    ]
