# Generated by Django 4.2.2 on 2023-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_alter_setores_nome_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
