# Generated by Django 4.2.2 on 2023-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_alter_representante_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='password',
            field=models.TextField(),
        ),
    ]
