# Generated by Django 4.2.2 on 2023-11-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_alter_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='telefone_representante',
            field=models.CharField(max_length=15),
        ),
    ]
