# Generated by Django 4.2.2 on 2023-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0007_alter_representante_telefone_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='ferias',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_funcionario',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone_funcionario',
            field=models.CharField(max_length=15),
        ),
    ]
