# Generated by Django 4.2.2 on 2023-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0008_funcionario_ferias_alter_funcionario_cpf_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
