# Generated by Django 4.2.2 on 2023-11-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0009_funcionario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
