# Generated by Django 4.2.2 on 2023-12-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0011_setores_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoramento.expediente'),
        ),
    ]
