# Generated by Django 4.2.2 on 2023-12-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0014_alter_funcionario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.funcionario'),
        ),
    ]
